Update read.py
KIT-HYD/bridget pull request #6
Opened 2020-04-29 12:00 UTC by AlexDo1

Added na_values (probably not the best way, but the only way I could get it running), resulting in the error:
`ValueError: Length mismatch: Expected axis has 54 elements, new values have 61 elements`
when using the read_TK2_file function to read in a csv file (as Mirko expected).

2020-04-29 12:11 UTC, mmaelicke requested changes
Looks good. I have some suggestions how we could work on the expected shape mismatch error

2020-04-29 12:11 UTC, mmaelicke commented on bridget/io/read.py
> +    return _reader(fname, 'TK2', strict=strict, **read_kwargs)
I would rather pass it as 
```python
return _reader(fname, 'TK2', strict=strict, read_kwargs=read_kwargs)
```
and undo the change below

2020-04-29 12:11 UTC, mmaelicke commented on bridget/io/read.py
> +def _reader(fname, type_str, strict=True, **read_kwargs):
I would keep the old version. See the changes above to make it work.

2020-04-29 12:11 UTC, mmaelicke commented on bridget/io/read.py
> -    data = pd.read_csv(fname, sep=',', header=None, index_col=None, **read_kwargs)
Here again, I would keep the old version.
The benefit is, that we can pass all the kwargs we want to further pass to read_csv. That enables us in the future to add another *_kwargs argument to the top-level function.

2020-04-29 12:11 UTC, mmaelicke commented on bridget/io/read.py
>      data.dropna(axis=1, how='all', inplace=True)
Colud you check if we loose the 7 coulmns full of NAN here, or already in the line above?

If we lose them here, we need a workaround. Maybe you can come up with something.

2020-04-29 14:05 UTC, mmaelicke commented
If you can't make my changes work, just let me know and I will work on it

2020-04-29 14:19 UTC, AlexDo1 commented
The changes for the usage of kwargs already work.

We are losing the columns with this line of code:
`data.dropna(axis=1, how='all', inplace=True)`
as some columns only consist of the number -9999.9003906 (replaced with NaN before) and so they are considered empty and are droped which leads to a mismatch with the given standard header values.
Commenting out the dropna line leads to the same error as we have an empty last column in the raw data which has to be dropped, otherwise we have a column too much. 

An easy workaround would be to delete the empty last column in the raw data but if this is a problem with all the expected input data files I should code soemthing that does that automatically.

2020-04-29 14:22 UTC, mmaelicke commented
Yes, I would prefer the 

>  code something that does that automatically

solution. Have you checked which columns are affected? Maybe we actually have to split them into mandatory and optional default columns.

2020-04-29 14:31 UTC, mmaelicke commented
Could work like:

1. Expand the default columns file with that 'NAN column', to make import and column header merging work.
2. Remove the dropna line
3.Explicitly drop the NAN column and import the others with possible NaN values

4. If `strict=True`, drop all columns that have NA and check if the columns array is still correct.

2020-04-30 13:10 UTC, AlexDo1 commented
Updated read.py and the default column file.
By deleting the na_column at the end of _reader should make `strict=True` work like  before.

2020-04-30 13:50 UTC, mmaelicke approved these changes
Looks good. I'll approve, although there is a minor thing that could be implemented

2020-04-30 13:50 UTC, mmaelicke commented on bridget/io/default_columns_TK2.csv
> +na_column,empty_column,delete_this_column_in_read_function
I like.

2020-04-30 13:50 UTC, mmaelicke commented on bridget/io/read.py
> +    # convert datetime columns to datetime data type
maybe we can add some kind of 
```python
if not df.t_begin.dtype in (datetime64, datetime):
  df['t_begin'] =  [...]
```
where `datetime` is the `datetime` class from the module of same name and the other one is from numpy I think
It's not super important, so you can accept the PR also without this fix. I think it's just better if the types are parsed correctly coming from another source

2020-04-30 14:59 UTC, AlexDo1 commented on bridget/io/read.py
> +    # convert datetime columns to datetime data type
I'm just trying to implement that. The problem ist that the columns of interest seem to be of the type datetime.datetime (as far as I understood it, datetime.datetime just looks if the input could be a date) so the if statement is not working.
But it is necessary to convert the columns with
`data['t_begin'] =  pd.to_datetime(data['t_begin'], format='%d.%m.%Y %H:%M')`
to plot the data.

2020-04-30 15:08 UTC, mmaelicke commented on bridget/io/read.py
> +    # convert datetime columns to datetime data type
`datetime.datetime` is the built-in date library in python. But as far as I understood it, the usage of `to_datetime`, with given format string converts `str` columns to datetime columns.

We could also always run that line and open another issue for implementing the if-clause.

2020-04-30 15:08 UTC, mmaelicke commented on bridget/io/read.py
> +    # convert datetime columns to datetime data type
I we will definitely have to implement some unittests as soon as we have the target data structure defined. But that's on me

2020-04-30 16:41 UTC, merged